# Text Classification Complete Solution

In [3]:
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/AI/trum_tweet_sentiment_analysis (1).csv")

df.head()

                                                text  Sentiment
0  RT @JohnLeguizamo: #trump not draining swamp b...          0
1  ICYMI: Hackers Rig FM Radio Stations To Play A...          0
2  Trump protests: LGBTQ rally in New York https:...          1
3  "Hi I'm Piers Morgan. David Beckham is awful b...          0
4  RT @GlennFranco68: Tech Firm Suing BuzzFeed fo...          0

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
# basic preprocessing
df = df[['text','Sentiment']].dropna()

df['text'] = df['text'].str.lower()

df.head()

                                                text  Sentiment
0  rt @johnleguizamo: #trump not draining swamp b...          0
1  icymi: hackers rig fm radio stations to play a...          0
2  trump protests: lgbtq rally in new york https:...          1
3  "hi i'm piers morgan. david beckham is awful b...          0
4  rt @glennfranco68: tech firm suing buzzfeed fo...          0

In [7]:
# train test split
from sklearn.model_selection import train_test_split

X = df['text']
y = df['Sentiment']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [8]:
# vectorization
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

In [9]:
# model training (Naive Bayes)
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_vec, y_train)

MultinomialNB()

In [12]:
# prediction
y_pred = model.predict(X_test_vec)

In [11]:
# evaluation
from sklearn.metrics import accuracy_score, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.8639281129653402
              precision    recall  f1-score   support

           0       0.84      0.99      0.91    248563
           1       0.97      0.60      0.74    121462

    accuracy                           0.86    370025
   macro avg       0.90      0.80      0.83    370025
weighted avg       0.88      0.86      0.85    370025